version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_taskforgelab
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - taskforge_network  # 🚀 Adicionando a rede compartilhada

volumes:
  pg_data:

networks:
  taskforge_network:
    external: true  # 🚀 Define que esta rede pode ser compartilhada entre projetos
